name: "TMC2130 Pen/Laser"
board: "TMC2130 Pen/Laser"

start:
  must_home: false

stepping:
  engine: RMT
  idle_ms: 255
  dir_delay_us: 1
  pulse_us: 2
  disable_delay_us: 0

kinematics:
  corexy:

axes:
  shared_stepper_disable_pin: gpio.13:high
  
  x:
    steps_per_mm: 320
    max_rate_mm_per_min: 16000
    acceleration_mm_per_sec2: 100
    max_travel_mm: 170
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 150.000
      feed_mm_per_min: 1000.000
      seek_mm_per_min: 4000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100
    
    motor0:
      limit_all_pin: gpio.32:low:pu
      tmc_2130:
        direction_pin: gpio.26:low
        step_pin: gpio.12
        cs_pin: gpio.17
        r_sense_ohms: 0.110
        run_amps: 0.8
        hold_amps: 0.250
        microsteps: 32
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: Stallguard
        use_enable: false
    motor1:
      null_motor:

  y:
    steps_per_mm: 320
    max_rate_mm_per_min: 16000
    acceleration_mm_per_sec2: 100
    max_travel_mm: 340
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 150.000
      feed_mm_per_min: 1000.000
      seek_mm_per_min: 4000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_all_pin: gpio.4:low:pu
      tmc_2130:
        direction_pin: gpio.25:high
        step_pin: gpio.14
        cs_pin: gpio.16
        r_sense_ohms: 0.110
        run_amps: 0.8
        hold_amps: 0.250
        microsteps: 32
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: Stallguard
        use_enable: false
    motor1:
      null_motor:

  z:
    steps_per_mm: 400
    max_rate_mm_per_min: 1000
    acceleration_mm_per_sec2: 50
    max_travel_mm: 5.00
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 5
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100
    motor0:
      rc_servo:
        pwm_hz: 50
        output_pin: gpio.27
        min_pulse_us: 500
        max_pulse_us: 1100
    motor1:
      null_motor:
        
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

coolant:
  flood_pin: NO_PIN
  mist_pin:  NO_PIN

probe:
  pin: NO_PIN

control:
  safety_door_pin: NO_PIN
